### ISSUE TITLE
pip install fails for pyjks 0.2

### ISSUE THREAD

**Issue by ashemedai** [doublereedkurt/pyjks#4]
On Ubuntu 14.04 with pip 1.5.6 on Python 2.7 when I try to install via pip install pyjks I get the following:

```
Downloading/unpacking pyjks
  Downloading pyjks-0.2.zip
  Running setup.py (path:/tmp/pip_build_root/pyjks/setup.py) egg_info for package pyjks
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pyjks/setup.py", line 11, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pyjks/setup.py", line 11, in <module>

    long_description=open('README.md').read(),

IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by mahmoud** [comment]
Reviving old threads, I think it's safe to say this is an issue we haven't seen in a while. I've added tox support recently, so it really shouldn't be happening again anytime soon, either :)
